name: ML CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Workflow-CI/MLProject/**'
  workflow_dispatch:

jobs:
  mlflow-build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: pip install mlflow pandas scikit-learn

      - name: Train model and get RUN_ID
        id: train
        run: |
          cd Workflow-CI/MLProject
          mlflow run . -P param=none --env-manager=local
          
          python modelling.py

          RUN_ID=$(ls -t mlruns/0 | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image via MLflow
        run: |
          cd Workflow-CI/MLProject
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n ${{ secrets.DOCKER_USERNAME }}/sistem-machine-learning-model:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/sistem-machine-learning-model:latest
