name: ML CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Workflow-CI/MLProject/**'
  workflow_dispatch:

jobs:
  ml-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: pip install mlflow==2.19.0 pandas scikit-learn

      - name: Run mlflow project
        run: |
          cd Workflow-CI/MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          cd Workflow-CI/MLProject
          # Cari experiment ID terlebih dahulu
          EXPERIMENT_ID=$(ls mlruns/ | grep -v trash | head -n 1)
          echo "Experiment ID: $EXPERIMENT_ID"
          # Cari run ID terbaru di dalam experiment
          RUN_ID=$(ls -t mlruns/$EXPERIMENT_ID/ | grep -v meta | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Ditemukan Run ID: $RUN_ID"

      - name: Install Python dependencies
        run: pip install mlflow==2.19.0

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: Workflow-CI/MLProject/mlruns/

      - name: Build Docker Model
        run: |
          cd Workflow-CI/MLProject
          EXPERIMENT_ID=$(ls mlruns/ | grep -v trash | head -n 1)
          mlflow models build-docker -m "mlruns/$EXPERIMENT_ID/${{ env.RUN_ID }}/artifacts/model" -n sistem-machine-learning-model:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag sistem-machine-learning-model:latest ${{ secrets.DOCKER_USERNAME }}/sistem-machine-learning-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sistem-machine-learning-model:latest
